allowBuilds:
  '@namchee/astro-subfont': false
  esbuild: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAgeExclude:
  - astro-xitter@1.2.1 || 1.2.3
onlyBuiltDependencies:
  - '@namchee/astro-subfont'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
