name: Run unit tests

on:
  - pull_request

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4
      - name: Instal pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.0
      - name: Install dependencies
        run: pnpm install
      - name: Run unit test
        run: pnpm run test
      - name: Check astro
        run: pnpm run check
