name: Sync webmentions

on:
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch:

jobs:
  webmentions-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.2
      - name: Install dependencies
        run: pnpm install
      - name: Sync webmentions
        env:
          WEBMENTIONS_API_KEY: ${{ secrets.WEBMENTIONS_API_KEY }}
        run: pnpm run webmentions:sync
      - name: Commit webmentions to repository
        env:
          COMMIT_MSG: |
            chore(webmentions): automated sync
        run: |
          git config user.email "cristophernamchee12@gmail.com"
          git config user.name "Cristopher Namchee"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)
      - name: Build the site
        run: pnpm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 1a99b52ba5412ca55475fdbec4e0ab26
          command: pages deploy dist --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }} --commit-dirty=true
